# fly.toml app configuration file generated for nabeats on 2023-11-07T17:11:29+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nabeats"
primary_region = "syd"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
